### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by WyvernIXTL** [pythops/tenere#25]
Even though this program is compatible with windows,
1. There is no binary release for windows.
2. The config location in readme is not valid for windows: 

dirs readme gives me:
```
dirs::config_dir();
// Lin: Some(/home/alice/.config)
// Win: Some(C:\Users\Alice\AppData\Roaming)
// Mac: Some(/Users/Alice/Library/Application Support)
```

The location should be reflected in the readme: `~/AppData/Roaming/tenere/config.toml`.

**Comment by pythops** [comment]
Sure, PRs are welcome :)

**Comment by WyvernIXTL** [comment]
I am using in [my project](https://github.com/WyvernIXTL/ubilerntui/blob/master/.github/workflows/compile-and-release-on-version-push.yml#L45) the [taiki-e/upload-rust-binary-action](https://github.com/taiki-e/upload-rust-binary-action).

Would that work for you too?
(Without hash maybe 😆 )

**Comment by pythops** [comment]
I am using the `softprops/action-gh-release` already in the CI so there is no need to change it.
maybe you can just add another step to cross compile to windows platform. something like this 
```
      - name: Build for Windows
        if: matrix.os == 'ubuntu-latest'
        run: |
          just build-release-windows
          cp target/x86_64-pc-windows-msvc/release/tenere tenere-x86_64-pc-windows-msvc
```
and in the Justfile, you can add the target
```
build-release-windows:
    @cargo build --release --target=x86_64-pc-windows-msvc
```

**Comment by WyvernIXTL** [comment]
I am wondering why you not do something like:
```yaml
build:
   strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
         runs-on: ${{ matrix.os }}
```

Then you do per build
`rustup target add ${{ matrix.target }}`

and just compile it with 
`cargo b -r --target ${{ matrix.target }} --out-dir ./`

Creating the release note can be put into another task and uploading should work in the matrix.
