### ISSUE TITLE
Very slow speed of text printed on screen compared to streaming speed from url endpoint.

### ISSUE THREAD

**Issue by mav3ri3k** [pythops/tenere#57]
The inference speed is very slow. I am using groq for the endpoint which returns text generally above 300 tks. However, in the tui its very slow. I think there is a limit somewhere for max tokens printed on screen.

Config: 
```toml
llm  = "chatgpt"

[chatgpt]
openai_api_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
model = "qwen-2.5-32b"
url = "https://api.groq.com/openai/v1/chat/completions"

```

Host System:
```toml
name = "Darwin"
os_version = "15.3.1"
long_os_version = "macOS 15.3.1 Sequoia"
kernel_version = "24.3.0"
```
